POST http://localhost:3000/api/register HTTP/1.1
content-type: application/json

{
    "username": "dicksonma98",
    "email": "dicksonma98@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/api/login 
content-type: application/json

{
    "username": "dicksonma96",
    "password": "123456"
}

###

POST http://localhost:3000/api/getUserDetail 
content-type: application/json

{
    "id": "12345"
}

###
GET http://localhost:3000/api/hello 
content-type: application/json


###

POST https://fitbuddy-middleware-database.vercel.app/api/register HTTP/1.1
content-type: application/json

{
    "username": "dicksonma97",
    "email": "dicksonma97@gmail.com",
    "password": "123456"
}


###

POST http://localhost:3000/api/userUpdate HTTP/1.1
content-type: application/json

{
   "user_id":"1234",
   "age":20,
   "gender": "m",
   "height" : 170,
   "weight" : 70,
   "target_weight" :75,
   "exercise_freq" : 0,
   "plank_last" : 0,
   "home_equip" : false
}

###

GET http://localhost:3000/api/getTutorials HTTP/1.1
content-type: application/json


###

GET http://localhost:3000/api/getFeaturedTutorials HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/getTutorialDetail?tutorial_id=1 HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/updateTutorial HTTP/1.1
content-type: application/json

{
   "id":1,
   "name":"Body Sculpting 2",
   "img_url": "https://images.pexels.com/photos/1431282/pexels-photo-1431282.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
   "time" : 10,
   "featured" : true,
   "premium" : true,
   "description":"Desc",
   "exercise" : [{
    "id":1,
    "name":"Push-ups",
    "description":"Start in a plank position with your hands slightly wider than shoulder-width apart. Lower your body until your chest nearly touches the floor, then push yourself back up to the starting position.",
    "reps":10,
    "tutorial_id":1
   }]
}

###


POST http://localhost:3000/api/addTutorial HTTP/1.1
content-type: application/json

{
   "name":"Body Sculpting 3",
   "img_url": "https://images.pexels.com/photos/1431282/pexels-photo-1431282.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
   "time" : 10,
   "featured" : true,
   "premium" : true,
   "description":"Desc3"
}

###


POST http://localhost:3000/api/addExercise HTTP/1.1
content-type: application/json

{
   "name":"Push-ups 2",
   "description":"Desc3",
   "reps":10,
   "duration":0,
   "tutorial_id":1
}

###

GET http://localhost:3000/api/userComplete?user_id=123 HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/markComplete HTTP/1.1
content-type: application/json

{
    "user_id":123,
    "tutorial_id":2
}

###

GET http://localhost:3000/api/completeStatus?user_id=123&tutorial_id=2 HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/createPlan HTTP/1.1
content-type: application/json

{
    "user_id":123,
    "name":"My Plan 2"
}

###

GET http://localhost:3000/api/getPlan?user_id=123 HTTP/1.1
content-type: application/json

###


POST http://localhost:3000/api/updatePlan HTTP/1.1
content-type: application/json

{
    "id":1,
    "tutorials":[1,2,3],
    "name":"My Plan 2"
}

###


DELETE http://localhost:3000/api/deletePlan?id=1 HTTP/1.1
content-type: application/json



INSERT INTO exercise (tutorial_id, name, reps, description) 
VALUES 
(1,
'Squats',
20,
'')

INSERT INTO tutorial (img_url, name, time, featured, premium) 
VALUES 
('https://images.pexels.com/photos/28076/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
'Slender Legs',
10,
true,true)


select user_complete.*, tutorial.name from user_complete LEFT JOIN tutorial ON user_complete.tutorial_id = tutorial.id where user_id = '123'




CREATE TABLE workout_plan (
id SERIAL PRIMARY KEY,
name VARCHAR(100),
user_id VARCHAR(255),
tutorials INTEGER[]
)